package structure

type State int64

const (
	STATE_ROOT State = iota
	STATE_ELEMENT
	STATE_ELEMENT_ID
	STATE_ELEMENT_CLASS
	STATE_ELEMENT_ATTRIBUTE
	STATE_CONTAINER
	STATE_STRING
	STATE_IMPORT
	STATE_VARIABLE_DEFINITION
	STATE_TEMPLATE
	STATE_VARIABLE_INSERT
	STATE_AT_STATEMENT
)
